# SPDX-FileCopyrightText: 2020 Marcel Märtens
# SPDX-FileCopyrightText: 2021 Forest Anderson <forestkzanderson@gmail.com>
# SPDX-FileCopyrightText: 2023 Javier Pérez
#
# SPDX-License-Identifier: CC0-1.0

stages:
  - check
  - publish

variables:
  # Note: this is deprecated!
  # https://docs.gitlab.com/ee/ci/yaml/#git-strategy
  # However in GitLab web UI it's set to fetch so it should be fine ¯\_(ツ)_/¯
  GIT_STRATEGY: fetch
  # Note: this is deprecated!
  # https://docs.gitlab.com/ee/ci/yaml/#shallow-cloning
  GIT_DEPTH: 3
  GIT_CLEAN_FLAGS: -f

default:
  image: ubuntu
  # https://docs.gitlab.com/ee/ci/pipelines/settings.html#auto-cancel-pending-pipelines
  interruptible: true
  # Retry automatically in case the runner times out or there's a runner failure
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

  before_script:
    # - source $HOME/.cargo/env
    - df -h /
    - free -h
    # - cargo --version
    - rm -rf target || echo "some quick fix, idk why needed"

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

include:
  - local: .gitlab/CI/check.gitlab-ci.yml
  - local: .gitlab/CI/publish.gitlab-ci.yml
