# SPDX-FileCopyrightText: 2018 Joshua Barretto <joshua@jsbarretto.com>
# SPDX-FileCopyrightText: 2020 Songtronix <contact@songtronix.com>
# SPDX-FileCopyrightText: 2020 Marcel Märtens
# SPDX-FileCopyrightText: 2021 - 2022 Vechro
# SPDX-FileCopyrightText: 2023 - 2024 Javier Pérez
#
# SPDX-License-Identifier: CC0-1.0

# Reference: https://www.getzola.org/documentation/getting-started/configuration/
# The base URL of the site; the only required configuration variable.
base_url = "https://veloren.net"

# The site title and description; used in feeds by default.
title = "Veloren"
description = "Veloren is an open-source action RPG set in a fantasy world made of voxels."

# When set to "true", the Sass files in the `sass` directory in the site root are compiled.
# Sass files in theme directories are always compiled.
compile_sass = true

# When set to "true", the generated HTML files are minified.
minify_html = true

# A list of glob patterns specifying asset files to ignore when the content
# directory is processed. Defaults to none, which means that all asset files are
# copied over to the `public` directory.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*", "**/build_folder"]
ignored_content = ["*.license"]

# When set to "true", a feed is automatically generated.
generate_feed = true

# The filename to use for the feed. Used as the template filename, too.
# Defaults to "atom.xml", which has a built-in template that renders an Atom 1.0 feed.
# There is also a built-in template "rss.xml" that renders an RSS 2.0 feed.
feed_filename = "rss.xml"

# When set to "true", files in the `static` directory are hard-linked. Useful for large
# static files. Note that for this to work, both `static` and the
# output directory need to be on the same filesystem. Note that the theme's `static`
# files are always copied, regardless of this setting.
hard_link_static = true

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = [
  {name = "tags"}
]

# Configuration of the Markdown rendering
[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true
