# SPDX-FileCopyrightText: 2021 Forest Anderson <forestkzanderson@gmail.com>
# SPDX-FileCopyrightText: 2023 Javier Pérez
#
# SPDX-License-Identifier: CC0-1.0

name: Mirror GitLab repo

# Every other day
on:
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  mirror-gitlab-repo:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone GitLab repo
        run: git lfs install;
          git clone https://gitlab.com/veloren/site.git;

      - name: Uninstall LFS
        run: cd site;
          git lfs uninstall;
          git lfs migrate export --include="*" --everything -y;

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          tags: true
          directory: site
