# SPDX-FileCopyrightText: 2020 Marcel Märtens
# SPDX-FileCopyrightText: 2021 - 2022 Forest Anderson <forestkzanderson@gmail.com>
# SPDX-FileCopyrightText: 2021 Vechro
# SPDX-FileCopyrightText: 2021 Fernando Pastorelli <fernando.n.p.d.moscu@gmail.com>
# SPDX-FileCopyrightText: 2023 Javier Pérez
#
# SPDX-License-Identifier: CC0-1.0

# Publishes veloren-server-cli to the GitLab container registry
# https://gitlab.com/veloren/veloren/container_registry
.publish:
  stage: publish
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: never

pages:
  extends: .publish
  image: ubuntu
  artifacts:
    paths:
      - public
  script:
    - apt update && apt install wget -y
    - wget -c https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz -O - | tar -xz
    - ./zola build
